Naspinski.FoodTruck.Admin/Controllers/ImagesController.cs
using Naspinski.Data.Interfaces;
using Naspinski.FoodTruck.AdminWeb.Models.Files;
using Naspinski.FoodTruck.AdminWeb.Services;
using Naspinski.FoodTruck.Data;
using Naspinski.FoodTruck.Data.Distribution.Models.System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Threading.Tasks;
using Naspinski.FoodTruck.Data.Distribution.Handlers.System;
using System.Linq;

namespace Naspinski.FoodTruck.AdminWeb.Controllers
{
    [Authorize]
    public class ImagesController : _BaseFoodTruckController
    {
        private ICrudHandler<ImageModel, FoodTruckContext, ImageModel> _handler;
        private readonly AzureSettings _azureSettings;

        public ImagesController(FoodTruckContext context, AzureSettings azureSettings) : base(context)
        {
            _azureSettings = azureSettings;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            _handler = new ImageHandler(_context, _user);
        }
        
        [HttpGet]
        public IActionResult Index(bool deleted = false)
        {
            ViewData["Deleted"] = deleted;
            return View(new ImageIndexModel() { Images = _handler.GetAll(deleted) });
        }

        [HttpPost]
        public async Task<IActionResult> Index(ImageIndexModel model)
        {
            var location = FileUploader.ProcessFormFile(_azureSettings.StorageAccount, _azureSettings.StorageAccountPassword, model.File, "images", ModelState, overwrite: true).Result.ToString();
            
            var exists = _handler.GetAll().FirstOrDefault(x => x.Location.Equals(location, System.StringComparison.InvariantCultureIgnoreCase));
            if (exists != null)
            {
                exists.Name = model.Name;
                exists.IsDeleted = false;
            }

            _handler.Upsert(exists == null ? new ImageModel() { Name = model.Name, Location = location } : exists);
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public IActionResult Delete(int id, bool isRestore = false)
        {
            if (isRestore) _handler.Restore(id);
            else _handler.Delete(id);
            return NoContent();
        }
    }
}

Naspinski.FoodTruck.Admin/Views/Images/Index.cshtml
@model Naspinski.FoodTruck.AdminWeb.Models.Files.ImageIndexModel
@{
    var deleted = ViewData["Deleted"].ToString() == "False";
}
<h2>
    @(!deleted ? "Deleted" : "") Images
    <a class="btn btn-default pull-right" asp-area="" asp-controller="Images" asp-action="Index" asp-route-deleted="@(deleted)">
        @(deleted ? "Deleted" : "Active") Items
    </a>
</h2>
<hr />
<form method="post" id="form-edit" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="File"></label>
                <input asp-for="File" type="file" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <br />
                <button type="submit" class="btn btn-default">
                    <i class="glyphicon glyphicon-floppy"></i>
                    Save
                </button>
            </div>
        </div>
    </div>
</form>
<hr />
<ul class="list-group">
    @if (!Model.Images.Any())
    {
        <li class="list-group-item">no images</li>}
    @foreach (var item in Model.Images)
    {
        <li class="list-group-item" id="item-@item.Id">
            <div class="row">
                <div class="col-sm-3">
                    <img class="pull-left" style="height:100px; margin-right:1em" src="@item.Location" />
                </div>
                <div class="col-sm-9">
                    <span class="pull-right" style="padding-left: 1em;">
                        <a class="btn btn-default item-delete" data-id="@item.Id" data-restore="@item.IsDeleted">
                            <i class="glyphicon @(item.IsDeleted ? "glyphicon-refresh" : "glyphicon-trash")"></i>
                        </a>
                    </span>
                    <h4>
                        <a href="@item.Location">@item.Name</a>
                    </h4>
                    <pre>@item.Location</pre>
                </div>
            </div>
        </li>
    }
</ul>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script>
        $(document).ready(function () {
            $('.item-delete').on('click', function (e) {
                const id = $(this).data('id');
                const restore = $(this).data('restore');
                e.preventDefault();
                $.ajax('/Images/Delete/' + id + '?isRestore=' + restore, {
                    type: 'Delete',
                    success: function (data) {
                        $.toast({ text: 'Deleted', icon: 'success' })
                        $('#item-' + id).remove();
                    },
                    error: function (data) {
                        $.toast({ text: 'Unknown error occurred', hideAfter: false, icon: 'error' })
                    }
                })
            });
        });
    </script>
}